### PR TITLE
Fix: livenet_module - Removed dependency exclusions that break image builds

### PR DESCRIPTION
**Pull request by thiagocardozo**
The livenet image optimization option is breaking image creation in RH8.4.
The package _diffutils_ is missed in images without selinux, and _cracklib-dicts_ is missed with and without selinux.
Removing both exclusions turns the "if self.selinux" block unnecessary.

### CODE REVIEW

**Comment by oxedions** [comment]
Dear @thiagocardozo 

Thanks a lot for this PR. I think this option should even be removed, and replaced by an "add custom parameters to packager" or something like that.

I let @pietersdavid have a look on this PR.

**Comment by pietersdavid** [comment]
Dear @thiagocardozo

Thank you for you PR. 

Maybe we can add the packages to exclude in a string array and add this array in the dnf command with the proper "--exclude"'s in order to have a cleaner code.

**Comment by thiagocardozo** [comment]
Hello @pietersdavid,

Sorry for my delay in answering. I agree with oxedions in that this "optimization" should become something parametrized.
Sure if we are to provide an exclusion list feature, we`ll have to remove those long static dnf lines in the code.

**Comment by oxedions** [comment]
Dear @thiagocardozo 
I think we can merge it as it, and improve it later, so fix is present in 1.5.0.

Are you ok to resolve your current conflict and update the PR ?

**Comment by oxedions** [comment]
Ok, I miss time to do advanced devs.

@thiagocardozo could you also increase version number for diskless set tool, and then it will be ok.
(Do it in the version.conf file, and also at top of disklessset file as a comment).

Then I will be able to merge it this way, and we can improve it later.

**Comment by thiagocardozo** [comment]
Done.

**Comment by oxedions** [comment]
Ok, thanks a lot. I solved the conflicts.

**Pull request merged**
